---
title: "Reproducible Research: Peer Assessment 2 (weather analysis)"
output: 
  html_document
---

## Introduction

## Sypnosis

We will answer 2 questions:

1. Which types of events are most damaging in the US?
2. Which types of events have the greatest economic consequences in the US?

### 1. Downloading Data

```{R}
zip_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
zip_filename <- "StormData.csv.bz2"
if(!file.exists(zip_filename)){
    download.file(zip_url, zip_filename, method="curl")
}
```

### 2. Loading dataset

```{R}
weather <- read.csv(zip_filename, header=TRUE, sep=",")
```

Data consists of `r dim(weather)[1]` row(s) and `r dim(weather)[2]` columns

Available columns:
```{R, echo=FALSE}
# List out column names
names(weather)
```

Head and tail of the data:
```{R}
head(weather)
```
```{R}
tail(weather)
```
### 3. Cleaning data

We need to create a subset with colums needed for the research.

EVTYPE - Type of event 
FATALITIES - Number of fatalities
INJURIES - Number of injured people 
PROPDMG - Property damage measurement
PROPDMGEXP - PROPDMG exponential
CROPDMG - Crop damage measurement
CROPDMGEXP - CROPDMG exponential

```{R, message=FALSE, warning=FALSE}
library(dplyr)
cleaned_df <- select(weather, EVTYPE, FATALITIES, INJURIES, PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP)
```

Check first 5 rows from subset dataset
```{R}
head(cleaned_df)
```

### 4. Analysing Data

#### 4.1 Most damaging events.

```{R}
tmp <- cleaned_df %>%
    group_by(EVTYPE) %>%
    summarise(health_affected = sum(FATALITIES + INJURIES)) %>%
    arrange(desc(health_affected))
top10 <- tmp[1:10,]
with(top10, barplot(height = health_affected, names.arg = EVTYPE, las = 3))
```

#### 4.2 Greatest economic impact due to events

Changing exp values - converting them to numbers

```{R}
tmp2 <- cleaned_df %>%
    mutate(actual_propdmg = case_when(.$PROPDMGEXP == "H" ~ .$PROPDMG*10^2,
                                      .$PROPDMGEXP == "K" ~ .$PROPDMG*10^3,
                                      .$PROPDMGEXP == "M" ~ .$PROPDMG*10^6,
                                      .$PROPDMGEXP == "B" ~ .$PROPDMG*10^9,
                                      TRUE ~ .$PROPDMG)) %>%
    mutate(actual_cropdmg = case_when(.$CROPDMGEXP == "H" ~ .$CROPDMG*10^2,
                                      .$CROPDMGEXP == "K" ~ .$CROPDMG*10^3,
                                      .$CROPDMGEXP == "M" ~ .$CROPDMG*10^6,
                                      .$CROPDMGEXP == "B" ~ .$CROPDMG*10^9,
                                      TRUE ~ .$CROPDMG)) %>%
    group_by(EVTYPE) %>%
    summarise(total_actual_damage = sum(actual_propdmg + actual_cropdmg)) %>%
    arrange(desc(total_actual_damage))
top10_2 <- tmp2[1:10,]
library(ggplot2)
ggplot(data=top10_2, aes(EVTYPE, total_actual_damage/10^3, fill=EVTYPE)) +
    geom_bar(stat="identity") +
    guides(fill=FALSE) +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```

## Results

We can say that tornados cause the most damage for killed and injured people (and second and third places are nowhere near this damage), and the economic damage is also big (third place overall). However, floods do more damage on economy overall